### PR TITLE
Add new Microsoft emojis to EmojiController.php

### PR DESCRIPTION
**Pull request by conventoangelo**
1. Changed `$cacheFreshAfter` to today to update all emojis.
2. Added Microsoft 3D Fluent Emojis to allowed styles.
3. Added Microsoft Teams to allowed styles (Microsoft 3D Fluent Emojis but animated).

### CODE REVIEW

**Review by benborgers — CHANGES_REQUESTED** [review]
Hi! These emojis look cool, didn't realize they were available. I don't think this code is syntactically valid — could you check that and update the PR?

**Comment by conventoangelo** [comment]
You're right, I forgot some commas. Thanks for pointing it out. I have now updated the PR (I guess... I'm not sure if what I did was right as this is the first time I would update a pull request. I just committed and pushed to the branch again).

**Comment by conventoangelo** [comment]
@benborgers can you review the changes?

**Comment by benborgers** [comment]
Sorry for the delay! I'm a little worried about the cost impact of raising that `$cacheFreshAfter` timestamp. I'm going to be rewriting emojicdn in the coming month or so anyway, and will include these emojis in the rewrite! Appreciate you bringing them to my attention!

**Pull request closed without merging**
